

CREATE OR ALTER PROCEDURE SP_LISTAR_AVISOS
AS
BEGIN
	SELECT [EMPRESA_CODIGO],[AVISO_CODIGO],[AVISO_DESCRIPCION],[AVISO_DETALLE] FROM [TBCAS_AVISOS]
END
GO


CREATE OR ALTER PROCEDURE SP_BUSQUEDA
@tipo numeric(18,0),
@fecha varchar(8),
@estado tinyint
AS
BEGIN
	SELECT A.[EMPRESA_CODIGO],A.[AVISO_CODIGO],[AVISO_DESCRIPCION],[AVISO_DETALLE] FROM [dbo].[TBCAS_AVISOS] A JOIN
	[TBCAS_AVISOS_PUBLICA] B ON A.[AVISO_CODIGO]=B.[AVISO_CODIGO] AND A.[EMPRESA_CODIGO]=B.[EMPRESA_CODIGO] 
	WHERE [AVISO_TIPO_NRO]=@tipo AND [AVISO_PUBFECHA]=@fecha AND [AVISO_PUBLICA_ESTADO_ID]=@estado
END
GO

select * from [TBCAS_AVISOS_PUBLICA]
GO

EXEC SP_BUSQUEDA 1,'02-03-20',1
GO

CREATE OR ALTER PROCEDURE SP_LISTAR_AVISO
@empresa_codigo varchar(4),
@aviso_numero numeric(18,0)
AS
BEGIN
	SELECT USUARI_NOMBRES,USUARI_APEPAT,B.AVISO_CODIGO,AVISO_PUBFECHA,AVISO_PUBHORA,AVISO_DETALLE
	FROM [TBCAS_AVISOS] A JOIN [TBCAS_AVISOS_PUBLICA] B 
	ON A.AVISO_CODIGO=B.AVISO_CODIGO AND A.EMPRESA_CODIGO=B.EMPRESA_CODIGO
	JOIN [TBUSUARI] C ON B.USUARI_CODIGO=C.USUARI_CODIGO
	WHERE A.[EMPRESA_CODIGO]=@empresa_codigo AND A.[AVISO_CODIGO]=@aviso_numero
END
GO

select*from [dbo].[TBCAS_AVISOS]
go

CREATE OR ALTER PROCEDURE SP_LISTAR_COMENTARIO
@empresa_codigo varchar(4),
@aviso_numero numeric(18,0)
AS
BEGIN
	SELECT USUARI_NOMBRES,USUARI_APEPAT,AVISOCOM_COMENTARIO,AVISOCOM_FECHA,AVISOCOM_HORA 
	FROM [TBCAS_AVISO_COMENTARIO] A JOIN [dbo].[TBUSUARI] B
	ON A.AVISOCOM_USUARIO=B.USUARI_CODIGO
	WHERE A.[EMPRESA_CODIGO]=@empresa_codigo AND A.[AVISO_CODIGO]=@aviso_numero
END
GO

CREATE OR ALTER PROCEDURE SP_LISTAR_ADJUNTOS
@empresa_codigo varchar(4),
@aviso_numero numeric(18,0)
AS
BEGIN
	SELECT A.[EMPRESA_CODIGO],B.[AVISO_CODIGO],[AVISOARCH_USUARIO],B.[AVISOARCH_CODIGO],[AVISO_ARCHIVO],[AVISO_RUTA],[AVISOARCH_SYS_EST]
	FROM [TBCAS_AVISO_ARCHIVO] A JOIN [TBCAS_AVISOS_ARCHIVO_XUSUARIO] B
	ON A.AVISO_CODIGO=B.AVISOARCH_CODIGO
	WHERE A.[EMPRESA_CODIGO]=@empresa_codigo AND A.[AVISO_CODIGO]=@aviso_numero
END
GO


SELECT *FROM
SELECT *FROM
SELECT *FROM [dbo].[TBCAS_AVISOS_PUBLICA]
SELECT * FROM [dbo].[TBCAS_AVISOS]
--SELECT *FROM [dbo].[TBCAS_AVISOS_ARCHIVO_XUSUARIO]
SELECT *FROM[dbo].[TBCAS_AVISO_ARCHIVO] A join [TBCAS_AVISOS] B on A.EMPRESA_CODIGO=B.EMPRESA_CODIGO AND A.AVISO_CODIGO=B.AVISO_CODIGO
WHERE A.EMPRESA_CODIGO=9999 AND A.AVISO_CODIGO=9999

INSERT INTO TBCAS_AVISOS (EMPRESA_CODIGO, AVISO_CODIGO, AVISO_TIPO_NRO, 
AVISO_REGFECHA, AVISO_REGHORA, AVISO_PUBFECHA, AVISO_PUBHORA, AVISO_DESCRIPCION, AVISO_SYS_EST, AVISO_DETALLE) 
VALUES (9999, 9999, 1, '01-03-20', '00:00', '02-03-20', '02:00', 'Aviso de prueba', 1, 
'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi ullam, porro voluptate magnam accusantium itaque, est! Amet laborum fuga numquam atque id minus eveniet dolorum, culpa harum aperiam at vitae.');

INSERT INTO TBCAS_AVISOS_PUBLICA (EMPRESA_CODIGO, USUARI_CODIGO, AVISO_CODIGO, /*sirve para gestionar usuario que visitan avisos*/
 AVISO_PUBLICA_ESTADO_ID, CANTIDAD) VALUES (9999, 9002, 9999, 1, 0);

INSERT INTO TBCAS_AVISO_ARCHIVO (EMPRESA_CODIGO, AVISO_CODIGO, AVISO_ARCHIVO, 
AVISO_RUTA, AVISO_SYS_EST, AVISOARCH_CODIGO, AVISOARCH_NROVECES) 
VALUES (9999, 9999, 'Redireccion', 'https://stackoverrun.com/es/q/202', 1, 7003,0);

INSERT INTO TBCAS_AVISOS_ARCHIVO_XUSUARIO (EMPRESA_CODIGO, AVISO_CODIGO, AVISOARCH_CODIGO, AVISOARCH_USUARIO, AVISOARCH_FECHA, AVISOARCH_HORA) 
VALUES (1001, 2001, 7001, 9001, '17-09-20', '09:00');
GO

CREATE OR ALTER PROCEDURE SP_LISTAR_TIPO
AS
BEGIN
	SELECT * FROM [dbo].[TBCAS_AVISOS_TIPO]
END
GO

CREATE OR ALTER PROCEDURE SP_LISTAR_ESTADO
AS
BEGIN
	SELECT * FROM [dbo].[TBCAS_AVISOS_ESTADO]
END
GO