//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa.EN
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ConexionDB : DbContext
    {
        public ConexionDB()
            : base("name=ConexionDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBCAS_AVISO_ARCHIVO> TBCAS_AVISO_ARCHIVO { get; set; }
        public virtual DbSet<TBCAS_AVISO_COMENTARIO> TBCAS_AVISO_COMENTARIO { get; set; }
        public virtual DbSet<TBCAS_AVISO_PUBLICA_ESTADO> TBCAS_AVISO_PUBLICA_ESTADO { get; set; }
        public virtual DbSet<TBCAS_AVISOS> TBCAS_AVISOS { get; set; }
        public virtual DbSet<TBCAS_AVISOS_ARCHIVO_XUSUARIO> TBCAS_AVISOS_ARCHIVO_XUSUARIO { get; set; }
        public virtual DbSet<TBCAS_AVISOS_ESTADO> TBCAS_AVISOS_ESTADO { get; set; }
        public virtual DbSet<TBCAS_AVISOS_PUBLICA> TBCAS_AVISOS_PUBLICA { get; set; }
        public virtual DbSet<TBCAS_AVISOS_TIPO> TBCAS_AVISOS_TIPO { get; set; }
        public virtual DbSet<TBUSUARI> TBUSUARI { get; set; }
    
        public virtual ObjectResult<SP_BUSCAR_USUARIO_Result> SP_BUSCAR_USUARIO(string p_usuari_codigo, string p_usuari_pass)
        {
            var p_usuari_codigoParameter = p_usuari_codigo != null ?
                new ObjectParameter("p_usuari_codigo", p_usuari_codigo) :
                new ObjectParameter("p_usuari_codigo", typeof(string));
    
            var p_usuari_passParameter = p_usuari_pass != null ?
                new ObjectParameter("p_usuari_pass", p_usuari_pass) :
                new ObjectParameter("p_usuari_pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BUSCAR_USUARIO_Result>("SP_BUSCAR_USUARIO", p_usuari_codigoParameter, p_usuari_passParameter);
        }
    
        public virtual ObjectResult<SP_LISTAR_ADJUNTOS_Result> SP_LISTAR_ADJUNTOS(string empresa_codigo, Nullable<decimal> aviso_numero)
        {
            var empresa_codigoParameter = empresa_codigo != null ?
                new ObjectParameter("empresa_codigo", empresa_codigo) :
                new ObjectParameter("empresa_codigo", typeof(string));
    
            var aviso_numeroParameter = aviso_numero.HasValue ?
                new ObjectParameter("aviso_numero", aviso_numero) :
                new ObjectParameter("aviso_numero", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LISTAR_ADJUNTOS_Result>("SP_LISTAR_ADJUNTOS", empresa_codigoParameter, aviso_numeroParameter);
        }
    
        public virtual ObjectResult<SP_LISTAR_AVISO_COMPLETO_Result> SP_LISTAR_AVISO_COMPLETO(string empresa_codigo, Nullable<decimal> aviso_numero)
        {
            var empresa_codigoParameter = empresa_codigo != null ?
                new ObjectParameter("empresa_codigo", empresa_codigo) :
                new ObjectParameter("empresa_codigo", typeof(string));
    
            var aviso_numeroParameter = aviso_numero.HasValue ?
                new ObjectParameter("aviso_numero", aviso_numero) :
                new ObjectParameter("aviso_numero", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LISTAR_AVISO_COMPLETO_Result>("SP_LISTAR_AVISO_COMPLETO", empresa_codigoParameter, aviso_numeroParameter);
        }
    
        public virtual ObjectResult<SP_LISTAR_AVISOS_Result> SP_LISTAR_AVISOS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LISTAR_AVISOS_Result>("SP_LISTAR_AVISOS");
        }
    
        public virtual ObjectResult<SP_LISTAR_COMENTARIO_Result> SP_LISTAR_COMENTARIO(string empresa_codigo, Nullable<decimal> aviso_numero)
        {
            var empresa_codigoParameter = empresa_codigo != null ?
                new ObjectParameter("empresa_codigo", empresa_codigo) :
                new ObjectParameter("empresa_codigo", typeof(string));
    
            var aviso_numeroParameter = aviso_numero.HasValue ?
                new ObjectParameter("aviso_numero", aviso_numero) :
                new ObjectParameter("aviso_numero", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LISTAR_COMENTARIO_Result>("SP_LISTAR_COMENTARIO", empresa_codigoParameter, aviso_numeroParameter);
        }
    
        public virtual ObjectResult<SP_LISTAR_ESTADO_Result> SP_LISTAR_ESTADO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LISTAR_ESTADO_Result>("SP_LISTAR_ESTADO");
        }
    
        public virtual ObjectResult<SP_LISTAR_TIPO_Result> SP_LISTAR_TIPO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LISTAR_TIPO_Result>("SP_LISTAR_TIPO");
        }
    
        public virtual int SP_NUEVO_COMENTARIO(string id_empresa, Nullable<decimal> id_aviso, string id_usuario, string aVISOCOM_COMENTARIO)
        {
            var id_empresaParameter = id_empresa != null ?
                new ObjectParameter("id_empresa", id_empresa) :
                new ObjectParameter("id_empresa", typeof(string));
    
            var id_avisoParameter = id_aviso.HasValue ?
                new ObjectParameter("id_aviso", id_aviso) :
                new ObjectParameter("id_aviso", typeof(decimal));
    
            var id_usuarioParameter = id_usuario != null ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(string));
    
            var aVISOCOM_COMENTARIOParameter = aVISOCOM_COMENTARIO != null ?
                new ObjectParameter("AVISOCOM_COMENTARIO", aVISOCOM_COMENTARIO) :
                new ObjectParameter("AVISOCOM_COMENTARIO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_NUEVO_COMENTARIO", id_empresaParameter, id_avisoParameter, id_usuarioParameter, aVISOCOM_COMENTARIOParameter);
        }
    }
}
