//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa.EN
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBCAS_AVISOS_PUBLICA
    {
        public string EMPRESA_CODIGO { get; set; }
        public string USUARI_CODIGO { get; set; }
        public decimal AVISO_CODIGO { get; set; }
        public byte AVISO_PUBLICA_ESTADO_ID { get; set; }
        public Nullable<decimal> CANTIDAD { get; set; }
    
        public virtual TBCAS_AVISO_PUBLICA_ESTADO TBCAS_AVISO_PUBLICA_ESTADO { get; set; }
        public virtual TBCAS_AVISOS TBCAS_AVISOS { get; set; }
        public virtual TBUSUARI TBUSUARI { get; set; }
    }
}
