//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa.EN
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBCAS_AVISO_PUBLICA_ESTADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBCAS_AVISO_PUBLICA_ESTADO()
        {
            this.TBCAS_AVISOS_PUBLICA = new HashSet<TBCAS_AVISOS_PUBLICA>();
        }
    
        public string AVISO_PUBLICA_ESTADO_DESCRIP { get; set; }
        public byte AVISO_PUBLICA_ESTADO_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBCAS_AVISOS_PUBLICA> TBCAS_AVISOS_PUBLICA { get; set; }
    }
}
