//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa.EN
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBCAS_AVISO_ARCHIVO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBCAS_AVISO_ARCHIVO()
        {
            this.TBCAS_AVISOS_ARCHIVO_XUSUARIO = new HashSet<TBCAS_AVISOS_ARCHIVO_XUSUARIO>();
        }
    
        public string EMPRESA_CODIGO { get; set; }
        public decimal AVISO_CODIGO { get; set; }
        public string AVISO_ARCHIVO { get; set; }
        public string AVISO_RUTA { get; set; }
        public string AVISO_SYS_CRE { get; set; }
        public string AVISO_SYS_EST { get; set; }
        public decimal AVISOARCH_CODIGO { get; set; }
        public Nullable<decimal> AVISOARCH_NROVECES { get; set; }
    
        public virtual TBCAS_AVISOS TBCAS_AVISOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBCAS_AVISOS_ARCHIVO_XUSUARIO> TBCAS_AVISOS_ARCHIVO_XUSUARIO { get; set; }
    }
}
