//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa.EN
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBCAS_AVISO_COMENTARIO
    {
        public string EMPRESA_CODIGO { get; set; }
        public decimal AVISO_CODIGO { get; set; }
        public decimal AVISOCOM_ID { get; set; }
        public string AVISOCOM_USUARIO { get; set; }
        public string AVISOCOM_COMENTARIO { get; set; }
        public string AVISOCOM_FECHA { get; set; }
        public string AVISOCOM_HORA { get; set; }
        public string AVISOCOM_SYS_EST { get; set; }
        public string AVISOCOM_SYS_CRE { get; set; }
    
        public virtual TBUSUARI TBUSUARI { get; set; }
        public virtual TBCAS_AVISOS TBCAS_AVISOS { get; set; }
    }
}
