//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa.EN
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBCAS_AVISOS_ARCHIVO_XUSUARIO
    {
        public string EMPRESA_CODIGO { get; set; }
        public decimal AVISO_CODIGO { get; set; }
        public decimal AVISOARCH_CODIGO { get; set; }
        public string AVISOARCH_USUARIO { get; set; }
        public string AVISOARCH_FECHA { get; set; }
        public string AVISOARCH_HORA { get; set; }
        public string AVISOARCH_SYS_EST { get; set; }
        public string AVISOARCH_SYS_CRE { get; set; }
    
        public virtual TBCAS_AVISO_ARCHIVO TBCAS_AVISO_ARCHIVO { get; set; }
    }
}
