//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa.EN
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBCAS_AVISOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBCAS_AVISOS()
        {
            this.TBCAS_AVISO_ARCHIVO = new HashSet<TBCAS_AVISO_ARCHIVO>();
            this.TBCAS_AVISO_COMENTARIO = new HashSet<TBCAS_AVISO_COMENTARIO>();
            this.TBCAS_AVISOS_PUBLICA = new HashSet<TBCAS_AVISOS_PUBLICA>();
        }
    
        public string EMPRESA_CODIGO { get; set; }
        public decimal AVISO_CODIGO { get; set; }
        public decimal AVISO_TIPO_NRO { get; set; }
        public string AVISO_REGFECHA { get; set; }
        public string AVISO_REGHORA { get; set; }
        public DateTime AVISO_PUBFECHA { get; set; }
        public string AVISO_PUBHORA { get; set; }
        public string AVISO_DESCRIPCION { get; set; }
        public string AVISO_SYS_EST { get; set; }
        public string AVISO_DETALLE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBCAS_AVISO_ARCHIVO> TBCAS_AVISO_ARCHIVO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBCAS_AVISO_COMENTARIO> TBCAS_AVISO_COMENTARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBCAS_AVISOS_PUBLICA> TBCAS_AVISOS_PUBLICA { get; set; }
        public virtual TBCAS_AVISOS_ESTADO TBCAS_AVISOS_ESTADO { get; set; }
        public virtual TBCAS_AVISOS_TIPO TBCAS_AVISOS_TIPO { get; set; }
    }
}
