//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa.EN
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBUSUARI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBUSUARI()
        {
            this.TBCAS_AVISO_COMENTARIO = new HashSet<TBCAS_AVISO_COMENTARIO>();
            this.TBCAS_AVISOS_PUBLICA = new HashSet<TBCAS_AVISOS_PUBLICA>();
        }
    
        public string USUARI_CODIGO { get; set; }
        public string USUARI_PASS { get; set; }
        public string USUARI_FECPASS { get; set; }
        public string USUARI_ESTADO { get; set; }
        public string USUARI_ESTASOCIADO { get; set; }
        public string USUARI_NIVEL { get; set; }
        public string USUARI_FECINI { get; set; }
        public string USUARI_FECFIN { get; set; }
        public string USUARI_DIAHORACC { get; set; }
        public string USUARI_ACCFER { get; set; }
        public string USUARI_NUMPASS { get; set; }
        public string USUARI_PASSANT { get; set; }
        public string USUARI_SYS_CRE { get; set; }
        public string USUARI_SYS_MOD { get; set; }
        public string USUARI_SYS_EST { get; set; }
        public string USUARI_APEPAT { get; set; }
        public string USUARI_APEMAT { get; set; }
        public string USUARI_NOMBRES { get; set; }
        public string USUARI_DOCIDENAC { get; set; }
        public string USUARI_TIPDOCIDE { get; set; }
        public string USUARI_CODDOCIDE { get; set; }
        public string USUARI_TIPO { get; set; }
        public string USUARI_TIPO_EXP { get; set; }
        public string USUARI_DIAS_EXP { get; set; }
        public string USUARI_CORREO { get; set; }
        public string PERSON_COD_INTERNO { get; set; }
        public string USUARI_TELEFONO { get; set; }
        public string USUARI_SEXO { get; set; }
        public string USUARI_FECHANAC { get; set; }
        public string USUARI_DIRECCION { get; set; }
        public string USUARI_PAIS { get; set; }
        public string USUARI_DPTO { get; set; }
        public string USUARI_PROV { get; set; }
        public string USUARI_DIST { get; set; }
        public string USUARI_EMPRESA { get; set; }
        public string USUARI_EMPRESA_OFICINA { get; set; }
        public string USUARI_EMPRESA_PUESTO { get; set; }
        public string USUARI_PROVEEDOR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBCAS_AVISO_COMENTARIO> TBCAS_AVISO_COMENTARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBCAS_AVISOS_PUBLICA> TBCAS_AVISOS_PUBLICA { get; set; }
    }
}
